### PR TITLE
add prairie vole to readme

### PR DESCRIPTION
**Pull request by PolarBean**
Just added the prairie vole info to the readme

### CODE REVIEW

**Comment by adamltyson** [comment]
This is a duplicate of #420.

Are the ages correct though? The methods section mentions 8-10 weeks specifically, but to me that read as referring to a specific protocol, not the ages of all animals.

**Comment by adamltyson** [comment]
Also, I think the template is LSFM, but they used STP to help annotate

**Comment by PolarBean** [comment]
oh my mistake! This is the part of the paper on which I am basing the age
image

**Comment by PolarBean** [comment]
oh yeah of course 🤦‍♂️

**Comment by adamltyson** [comment]
I only noticed it said mice when you posted it! I'd already read it 2x!

**Pull request closed without merging**
