### PR TITLE
Hemisphere improvements to axolotl atlas

### LINKED ISSUE #437: [BUG] Duplicate entries in acronyms in axolotl atlas?
**Describe the bug**
https://forum.image.sc/t/axolotl-atlas-has-duplicate-acronyms/105794

### PR DESCRIPTION
**Pull request by alessandrofelder**
## Description

**What is this PR**

- [x] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**Why is this PR needed?**
The UNAM axolotl atlas is asymmetric and has duplicate region acronyms (because the same region exists in each hemisphere)

**What does this PR do?**
- Computes and adds the (asymmetric) hemisphere stack for the axolotl atlas
- distinguishes duplicate region acronyms by labelling them L or R

## References

First tickbox of #359 
Closes #437 

## How has this PR been tested?

Visual inspection and validation script on local axolotl atlas.

## Is this a breaking change?

No

## Does this PR require an update to the documentation?

No

### CODE REVIEW

**Comment by adamltyson** [comment]
> distinguishes duplicate region acronyms by labelling them L or R

Do we need this? The whole point of the hemispheres stack is so that we don't have seperate regions for L & R.

**Comment by adamltyson** [comment]
All our other atlases have the same region (and acronym) in L & R hemispheres. The hemisphere is then encoded by the image.

**Comment by alessandrofelder** [comment]
> Does this atlas have different numerical IDs in each hemisphere?

Yep, it does.

>Does this atlas have different numerical IDs in each hemisphere? If so, this is what should be corrected to meet the BrainGlobe spec. 

OK!

**Comment by adamltyson** [comment]
I guess this should be added to the list of things that need to be documented 😞

**Comment by alessandrofelder** [comment]
> I guess this should be added to the list of things that need to be documented

https://github.com/brainglobe/brainglobe-atlasapi/pull/438

I've address the comments, and think this is ready now :)

**Review by adamltyson — APPROVED** [review]

**Pull request merged**
