### PR TITLE
Fixing human atlas script

### LINKED ISSUE #275: validate_atlases.py additional_references error
**Describe the bug**

- When I tried to run `validate_atlases.py` both in an interactive session on the HPC and as a submitted job I received this error: 

```
allen_human_500um 0.1
/nfs/nhome/live/vplattner/_projects/validation/brainglobe-atlasapi/brainglobe_atlasapi/core.py:65: UserWarning: This atlas seems to be outdated as no additional_references list is found in metadata!
  warnings.warn(
Traceback (most recent call last):
  File "/nfs/nhome/live/vplattner/_projects/validation/brainglobe-atlasapi/brainglobe_atlasapi/atlas_generation/validate_atlases.py", line 252, in <module>
    temp_validation_results = validate_atlas(
                              ^^^^^^^^^^^^^^^
  File "/nfs/nhome/live/vplattner/_projects/validation/brainglobe-atlasapi/brainglobe_atlasapi/atlas_generation/validate_atlases.py", line 222, in validate_atlas
    validation_function(BrainGlobeAtlas(atlas_name))
  File "/nfs/nhome/live/vplattner/_projects/validation/brainglobe-atlasapi/brainglobe_atlasapi/atlas_generation/validate_atlases.py", line 132, in validate_additional_references
    ) in atlas.additional_references.references_list:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BrainGlobeAtlas' object has no attribute 'additional_references'
```
- I manually removed all `additional_references` related functions and tests in the local code to be able to run the validation.  

**To Reproduce**

```
module load mamba
mamba init
mamba activate bg-atlasapi
git clone https://github.com/brainglobe/brainglobe-atlasapi.git
cd brainglobe-atlasapi/
git checkout main

pip install -e ".[allenmouse, dev]"
pip install scikit-image
pip install imio
pip install brainio

python brainglobe_atlasapi/atlas_generation/validate_atlases.py
```

**Computer used (please complete the following information):**

- OS: Linux 
- submitted job on HPC or interactive conda environment

### PR DESCRIPTION
**Pull request by viktorpm**
## Description

**What is this PR?**

- [x] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**What does this PR do?**

- Fixes `humanatlas.py` atlas generation script. 
- Automates the annotation and reference downloading steps.
- Fixes #275

## How has this PR been tested?

- locally
- on the HPC
- the regenerated atlas was validated

## Is this a breaking change?

no

## Does this PR require an update to the documentation?

no

## Checklist:

- [x] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Comment by viktorpm** [comment]
Meshes and image extent don't match. It needs to be fixed.

**Comment by viktorpm** [comment]
scaling is fixed

**Review by alessandrofelder — COMMENTED** [review]
As discussed in person
* it looks like we ignore the nifti header, and the raw array data is oriented in `rpi`
* we should run again with this, and add this info the header
* it would be useful to provide the whole brain in the script (not just one of the hemispheres)

annotations both hemisphere link: http://download.alleninstitute.org/informatics-archive/allen_human_reference_atlas_3d_2020/version_1/annotation_full.nii.gz

**Review by alessandrofelder — APPROVED** [review]
Looks good. Also sanity check of the packaged atlas looks good. I'll let you upload to GIN and merge this when it's done @viktorpm . Thank you :tada:

**Comment by adamltyson** [comment]
Thanks @viktorpm!

**Pull request merged**
